name: "Configure AWS and Retrieve Secrets"
description: "Authorize GitHub Actions to AWS and Get Secrets from Secret Manager"
inputs:
  account-id:
    description: "AWS Account ID"
    required: true
  role-name:
    description: "The name of the role to assume"
    required: true
  region:
    description: "The AWS region"
    default: "ap-southeast-2"
  session-name:
    description: "The name of the session"
    default: "configure-retrieve-aws-secrets"
  secret-branch: 
    description: "The branch to use for the secrets github.com/<repo>/secrets/<branch>"
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account-id }}:role/${{ inputs.role-name }}
        role-session-name: ${{ inputs.session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Retrieve Secrets from AWS Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          , github.com/${{ github.repository }}/secrets/${{ inputs.secret-branch }}
        parse-json-secrets: true
